server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://103.71.21.122:5433/vacancy_service
    username: postgres
    password: Nika12102014
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss

# ↓↓↓ ВАЖНО ДЛЯ ПРОКСИРОВАНИЯ АВТОРИЗАЦИИ ↓↓↓
auth:
  service:
    url: ${AUTH_SERVICE_URL:https://api.subscriptionhhapp.ru}

app:
  hhru:
    base-url: https://api.hh.ru
    timeout: 10000
    requests-per-second: 10

logging:
  level:
    com.mkisten.vacancybackend: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
