server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://postgres:5433/${POSTGRES_DB:vacancy_service}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Изменил на validate чтобы не конфликтовать с init.sql
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  jackson:
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://subscription_backend:8080}

app:
  hhru:
    base-url: https://api.hh.ru
    timeout: 10000
    requests-per-second: 10

logging:
  level:
    com.mkisten.vacancybackend: INFO
    org.hibernate.SQL: WARN
    org.springframework.security: WARN